//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::{
    channel::Entity as Channel, command_macro::Entity as CommandMacro, guild::Entity as Guild,
    reminder::Entity as Reminder, reminder_template::Entity as ReminderTemplate,
    seaql_migrations::Entity as SeaqlMigrations, timer::Entity as Timer, todo::Entity as Todo,
    user::Entity as User,
};
