//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "timezone")]
pub enum Timezone {
    #[sea_orm(string_value = "Africa/Abidjan")]
    AfricaAbidjan,
    #[sea_orm(string_value = "Africa/Accra")]
    AfricaAccra,
    #[sea_orm(string_value = "Africa/Addis_Ababa")]
    AfricaAddisAbaba,
    #[sea_orm(string_value = "Africa/Algiers")]
    AfricaAlgiers,
    #[sea_orm(string_value = "Africa/Asmara")]
    AfricaAsmara,
    #[sea_orm(string_value = "Africa/Asmera")]
    AfricaAsmera,
    #[sea_orm(string_value = "Africa/Bamako")]
    AfricaBamako,
    #[sea_orm(string_value = "Africa/Bangui")]
    AfricaBangui,
    #[sea_orm(string_value = "Africa/Banjul")]
    AfricaBanjul,
    #[sea_orm(string_value = "Africa/Bissau")]
    AfricaBissau,
    #[sea_orm(string_value = "Africa/Blantyre")]
    AfricaBlantyre,
    #[sea_orm(string_value = "Africa/Brazzaville")]
    AfricaBrazzaville,
    #[sea_orm(string_value = "Africa/Bujumbura")]
    AfricaBujumbura,
    #[sea_orm(string_value = "Africa/Cairo")]
    AfricaCairo,
    #[sea_orm(string_value = "Africa/Casablanca")]
    AfricaCasablanca,
    #[sea_orm(string_value = "Africa/Ceuta")]
    AfricaCeuta,
    #[sea_orm(string_value = "Africa/Conakry")]
    AfricaConakry,
    #[sea_orm(string_value = "Africa/Dakar")]
    AfricaDakar,
    #[sea_orm(string_value = "Africa/Dar_es_Salaam")]
    AfricaDarEsSalaam,
    #[sea_orm(string_value = "Africa/Djibouti")]
    AfricaDjibouti,
    #[sea_orm(string_value = "Africa/Douala")]
    AfricaDouala,
    #[sea_orm(string_value = "Africa/El_Aaiun")]
    AfricaElAaiun,
    #[sea_orm(string_value = "Africa/Freetown")]
    AfricaFreetown,
    #[sea_orm(string_value = "Africa/Gaborone")]
    AfricaGaborone,
    #[sea_orm(string_value = "Africa/Harare")]
    AfricaHarare,
    #[sea_orm(string_value = "Africa/Johannesburg")]
    AfricaJohannesburg,
    #[sea_orm(string_value = "Africa/Juba")]
    AfricaJuba,
    #[sea_orm(string_value = "Africa/Kampala")]
    AfricaKampala,
    #[sea_orm(string_value = "Africa/Khartoum")]
    AfricaKhartoum,
    #[sea_orm(string_value = "Africa/Kigali")]
    AfricaKigali,
    #[sea_orm(string_value = "Africa/Kinshasa")]
    AfricaKinshasa,
    #[sea_orm(string_value = "Africa/Lagos")]
    AfricaLagos,
    #[sea_orm(string_value = "Africa/Libreville")]
    AfricaLibreville,
    #[sea_orm(string_value = "Africa/Lome")]
    AfricaLome,
    #[sea_orm(string_value = "Africa/Luanda")]
    AfricaLuanda,
    #[sea_orm(string_value = "Africa/Lubumbashi")]
    AfricaLubumbashi,
    #[sea_orm(string_value = "Africa/Lusaka")]
    AfricaLusaka,
    #[sea_orm(string_value = "Africa/Malabo")]
    AfricaMalabo,
    #[sea_orm(string_value = "Africa/Maputo")]
    AfricaMaputo,
    #[sea_orm(string_value = "Africa/Maseru")]
    AfricaMaseru,
    #[sea_orm(string_value = "Africa/Mbabane")]
    AfricaMbabane,
    #[sea_orm(string_value = "Africa/Mogadishu")]
    AfricaMogadishu,
    #[sea_orm(string_value = "Africa/Monrovia")]
    AfricaMonrovia,
    #[sea_orm(string_value = "Africa/Nairobi")]
    AfricaNairobi,
    #[sea_orm(string_value = "Africa/Ndjamena")]
    AfricaNdjamena,
    #[sea_orm(string_value = "Africa/Niamey")]
    AfricaNiamey,
    #[sea_orm(string_value = "Africa/Nouakchott")]
    AfricaNouakchott,
    #[sea_orm(string_value = "Africa/Ouagadougou")]
    AfricaOuagadougou,
    #[sea_orm(string_value = "Africa/Porto-Novo")]
    AfricaPortoNovo,
    #[sea_orm(string_value = "Africa/Sao_Tome")]
    AfricaSaoTome,
    #[sea_orm(string_value = "Africa/Timbuktu")]
    AfricaTimbuktu,
    #[sea_orm(string_value = "Africa/Tripoli")]
    AfricaTripoli,
    #[sea_orm(string_value = "Africa/Tunis")]
    AfricaTunis,
    #[sea_orm(string_value = "Africa/Windhoek")]
    AfricaWindhoek,
    #[sea_orm(string_value = "America/Adak")]
    AmericaAdak,
    #[sea_orm(string_value = "America/Anchorage")]
    AmericaAnchorage,
    #[sea_orm(string_value = "America/Anguilla")]
    AmericaAnguilla,
    #[sea_orm(string_value = "America/Antigua")]
    AmericaAntigua,
    #[sea_orm(string_value = "America/Araguaina")]
    AmericaAraguaina,
    #[sea_orm(string_value = "America/Argentina/Buenos_Aires")]
    AmericaArgentinaBuenosAires,
    #[sea_orm(string_value = "America/Argentina/Catamarca")]
    AmericaArgentinaCatamarca,
    #[sea_orm(string_value = "America/Argentina/ComodRivadavia")]
    AmericaArgentinaComodRivadavia,
    #[sea_orm(string_value = "America/Argentina/Cordoba")]
    AmericaArgentinaCordoba,
    #[sea_orm(string_value = "America/Argentina/Jujuy")]
    AmericaArgentinaJujuy,
    #[sea_orm(string_value = "America/Argentina/La_Rioja")]
    AmericaArgentinaLaRioja,
    #[sea_orm(string_value = "America/Argentina/Mendoza")]
    AmericaArgentinaMendoza,
    #[sea_orm(string_value = "America/Argentina/Rio_Gallegos")]
    AmericaArgentinaRioGallegos,
    #[sea_orm(string_value = "America/Argentina/Salta")]
    AmericaArgentinaSalta,
    #[sea_orm(string_value = "America/Argentina/San_Juan")]
    AmericaArgentinaSanJuan,
    #[sea_orm(string_value = "America/Argentina/San_Luis")]
    AmericaArgentinaSanLuis,
    #[sea_orm(string_value = "America/Argentina/Tucuman")]
    AmericaArgentinaTucuman,
    #[sea_orm(string_value = "America/Argentina/Ushuaia")]
    AmericaArgentinaUshuaia,
    #[sea_orm(string_value = "America/Aruba")]
    AmericaAruba,
    #[sea_orm(string_value = "America/Asuncion")]
    AmericaAsuncion,
    #[sea_orm(string_value = "America/Atikokan")]
    AmericaAtikokan,
    #[sea_orm(string_value = "America/Atka")]
    AmericaAtka,
    #[sea_orm(string_value = "America/Bahia")]
    AmericaBahia,
    #[sea_orm(string_value = "America/Bahia_Banderas")]
    AmericaBahiaBanderas,
    #[sea_orm(string_value = "America/Barbados")]
    AmericaBarbados,
    #[sea_orm(string_value = "America/Belem")]
    AmericaBelem,
    #[sea_orm(string_value = "America/Belize")]
    AmericaBelize,
    #[sea_orm(string_value = "America/Blanc-Sablon")]
    AmericaBlancSablon,
    #[sea_orm(string_value = "America/Boa_Vista")]
    AmericaBoaVista,
    #[sea_orm(string_value = "America/Bogota")]
    AmericaBogota,
    #[sea_orm(string_value = "America/Boise")]
    AmericaBoise,
    #[sea_orm(string_value = "America/Buenos_Aires")]
    AmericaBuenosAires,
    #[sea_orm(string_value = "America/Cambridge_Bay")]
    AmericaCambridgeBay,
    #[sea_orm(string_value = "America/Campo_Grande")]
    AmericaCampoGrande,
    #[sea_orm(string_value = "America/Cancun")]
    AmericaCancun,
    #[sea_orm(string_value = "America/Caracas")]
    AmericaCaracas,
    #[sea_orm(string_value = "America/Catamarca")]
    AmericaCatamarca,
    #[sea_orm(string_value = "America/Cayenne")]
    AmericaCayenne,
    #[sea_orm(string_value = "America/Cayman")]
    AmericaCayman,
    #[sea_orm(string_value = "America/Chicago")]
    AmericaChicago,
    #[sea_orm(string_value = "America/Chihuahua")]
    AmericaChihuahua,
    #[sea_orm(string_value = "America/Coral_Harbour")]
    AmericaCoralHarbour,
    #[sea_orm(string_value = "America/Cordoba")]
    AmericaCordoba,
    #[sea_orm(string_value = "America/Costa_Rica")]
    AmericaCostaRica,
    #[sea_orm(string_value = "America/Creston")]
    AmericaCreston,
    #[sea_orm(string_value = "America/Cuiaba")]
    AmericaCuiaba,
    #[sea_orm(string_value = "America/Curacao")]
    AmericaCuracao,
    #[sea_orm(string_value = "America/Danmarkshavn")]
    AmericaDanmarkshavn,
    #[sea_orm(string_value = "America/Dawson")]
    AmericaDawson,
    #[sea_orm(string_value = "America/Dawson_Creek")]
    AmericaDawsonCreek,
    #[sea_orm(string_value = "America/Denver")]
    AmericaDenver,
    #[sea_orm(string_value = "America/Detroit")]
    AmericaDetroit,
    #[sea_orm(string_value = "America/Dominica")]
    AmericaDominica,
    #[sea_orm(string_value = "America/Edmonton")]
    AmericaEdmonton,
    #[sea_orm(string_value = "America/Eirunepe")]
    AmericaEirunepe,
    #[sea_orm(string_value = "America/El_Salvador")]
    AmericaElSalvador,
    #[sea_orm(string_value = "America/Ensenada")]
    AmericaEnsenada,
    #[sea_orm(string_value = "America/Fort_Nelson")]
    AmericaFortNelson,
    #[sea_orm(string_value = "America/Fort_Wayne")]
    AmericaFortWayne,
    #[sea_orm(string_value = "America/Fortaleza")]
    AmericaFortaleza,
    #[sea_orm(string_value = "America/Glace_Bay")]
    AmericaGlaceBay,
    #[sea_orm(string_value = "America/Godthab")]
    AmericaGodthab,
    #[sea_orm(string_value = "America/Goose_Bay")]
    AmericaGooseBay,
    #[sea_orm(string_value = "America/Grand_Turk")]
    AmericaGrandTurk,
    #[sea_orm(string_value = "America/Grenada")]
    AmericaGrenada,
    #[sea_orm(string_value = "America/Guadeloupe")]
    AmericaGuadeloupe,
    #[sea_orm(string_value = "America/Guatemala")]
    AmericaGuatemala,
    #[sea_orm(string_value = "America/Guayaquil")]
    AmericaGuayaquil,
    #[sea_orm(string_value = "America/Guyana")]
    AmericaGuyana,
    #[sea_orm(string_value = "America/Halifax")]
    AmericaHalifax,
    #[sea_orm(string_value = "America/Havana")]
    AmericaHavana,
    #[sea_orm(string_value = "America/Hermosillo")]
    AmericaHermosillo,
    #[sea_orm(string_value = "America/Indiana/Indianapolis")]
    AmericaIndianaIndianapolis,
    #[sea_orm(string_value = "America/Indiana/Knox")]
    AmericaIndianaKnox,
    #[sea_orm(string_value = "America/Indiana/Marengo")]
    AmericaIndianaMarengo,
    #[sea_orm(string_value = "America/Indiana/Petersburg")]
    AmericaIndianaPetersburg,
    #[sea_orm(string_value = "America/Indiana/Tell_City")]
    AmericaIndianaTellCity,
    #[sea_orm(string_value = "America/Indiana/Vevay")]
    AmericaIndianaVevay,
    #[sea_orm(string_value = "America/Indiana/Vincennes")]
    AmericaIndianaVincennes,
    #[sea_orm(string_value = "America/Indiana/Winamac")]
    AmericaIndianaWinamac,
    #[sea_orm(string_value = "America/Indianapolis")]
    AmericaIndianapolis,
    #[sea_orm(string_value = "America/Inuvik")]
    AmericaInuvik,
    #[sea_orm(string_value = "America/Iqaluit")]
    AmericaIqaluit,
    #[sea_orm(string_value = "America/Jamaica")]
    AmericaJamaica,
    #[sea_orm(string_value = "America/Jujuy")]
    AmericaJujuy,
    #[sea_orm(string_value = "America/Juneau")]
    AmericaJuneau,
    #[sea_orm(string_value = "America/Kentucky/Louisville")]
    AmericaKentuckyLouisville,
    #[sea_orm(string_value = "America/Kentucky/Monticello")]
    AmericaKentuckyMonticello,
    #[sea_orm(string_value = "America/Knox_IN")]
    AmericaKnoxIn,
    #[sea_orm(string_value = "America/Kralendijk")]
    AmericaKralendijk,
    #[sea_orm(string_value = "America/La_Paz")]
    AmericaLaPaz,
    #[sea_orm(string_value = "America/Lima")]
    AmericaLima,
    #[sea_orm(string_value = "America/Los_Angeles")]
    AmericaLosAngeles,
    #[sea_orm(string_value = "America/Louisville")]
    AmericaLouisville,
    #[sea_orm(string_value = "America/Lower_Princes")]
    AmericaLowerPrinces,
    #[sea_orm(string_value = "America/Maceio")]
    AmericaMaceio,
    #[sea_orm(string_value = "America/Managua")]
    AmericaManagua,
    #[sea_orm(string_value = "America/Manaus")]
    AmericaManaus,
    #[sea_orm(string_value = "America/Marigot")]
    AmericaMarigot,
    #[sea_orm(string_value = "America/Martinique")]
    AmericaMartinique,
    #[sea_orm(string_value = "America/Matamoros")]
    AmericaMatamoros,
    #[sea_orm(string_value = "America/Mazatlan")]
    AmericaMazatlan,
    #[sea_orm(string_value = "America/Mendoza")]
    AmericaMendoza,
    #[sea_orm(string_value = "America/Menominee")]
    AmericaMenominee,
    #[sea_orm(string_value = "America/Merida")]
    AmericaMerida,
    #[sea_orm(string_value = "America/Metlakatla")]
    AmericaMetlakatla,
    #[sea_orm(string_value = "America/Mexico_City")]
    AmericaMexicoCity,
    #[sea_orm(string_value = "America/Miquelon")]
    AmericaMiquelon,
    #[sea_orm(string_value = "America/Moncton")]
    AmericaMoncton,
    #[sea_orm(string_value = "America/Monterrey")]
    AmericaMonterrey,
    #[sea_orm(string_value = "America/Montevideo")]
    AmericaMontevideo,
    #[sea_orm(string_value = "America/Montreal")]
    AmericaMontreal,
    #[sea_orm(string_value = "America/Montserrat")]
    AmericaMontserrat,
    #[sea_orm(string_value = "America/Nassau")]
    AmericaNassau,
    #[sea_orm(string_value = "America/New_York")]
    AmericaNewYork,
    #[sea_orm(string_value = "America/Nipigon")]
    AmericaNipigon,
    #[sea_orm(string_value = "America/Nome")]
    AmericaNome,
    #[sea_orm(string_value = "America/Noronha")]
    AmericaNoronha,
    #[sea_orm(string_value = "America/North_Dakota/Beulah")]
    AmericaNorthDakotaBeulah,
    #[sea_orm(string_value = "America/North_Dakota/Center")]
    AmericaNorthDakotaCenter,
    #[sea_orm(string_value = "America/North_Dakota/New_Salem")]
    AmericaNorthDakotaNewSalem,
    #[sea_orm(string_value = "America/Nuuk")]
    AmericaNuuk,
    #[sea_orm(string_value = "America/Ojinaga")]
    AmericaOjinaga,
    #[sea_orm(string_value = "America/Panama")]
    AmericaPanama,
    #[sea_orm(string_value = "America/Pangnirtung")]
    AmericaPangnirtung,
    #[sea_orm(string_value = "America/Paramaribo")]
    AmericaParamaribo,
    #[sea_orm(string_value = "America/Phoenix")]
    AmericaPhoenix,
    #[sea_orm(string_value = "America/Port-au-Prince")]
    AmericaPortAuPrince,
    #[sea_orm(string_value = "America/Port_of_Spain")]
    AmericaPortOfSpain,
    #[sea_orm(string_value = "America/Porto_Acre")]
    AmericaPortoAcre,
    #[sea_orm(string_value = "America/Porto_Velho")]
    AmericaPortoVelho,
    #[sea_orm(string_value = "America/Puerto_Rico")]
    AmericaPuertoRico,
    #[sea_orm(string_value = "America/Punta_Arenas")]
    AmericaPuntaArenas,
    #[sea_orm(string_value = "America/Rainy_River")]
    AmericaRainyRiver,
    #[sea_orm(string_value = "America/Rankin_Inlet")]
    AmericaRankinInlet,
    #[sea_orm(string_value = "America/Recife")]
    AmericaRecife,
    #[sea_orm(string_value = "America/Regina")]
    AmericaRegina,
    #[sea_orm(string_value = "America/Resolute")]
    AmericaResolute,
    #[sea_orm(string_value = "America/Rio_Branco")]
    AmericaRioBranco,
    #[sea_orm(string_value = "America/Rosario")]
    AmericaRosario,
    #[sea_orm(string_value = "America/Santa_Isabel")]
    AmericaSantaIsabel,
    #[sea_orm(string_value = "America/Santarem")]
    AmericaSantarem,
    #[sea_orm(string_value = "America/Santiago")]
    AmericaSantiago,
    #[sea_orm(string_value = "America/Santo_Domingo")]
    AmericaSantoDomingo,
    #[sea_orm(string_value = "America/Sao_Paulo")]
    AmericaSaoPaulo,
    #[sea_orm(string_value = "America/Scoresbysund")]
    AmericaScoresbysund,
    #[sea_orm(string_value = "America/Shiprock")]
    AmericaShiprock,
    #[sea_orm(string_value = "America/Sitka")]
    AmericaSitka,
    #[sea_orm(string_value = "America/St_Barthelemy")]
    AmericaStBarthelemy,
    #[sea_orm(string_value = "America/St_Johns")]
    AmericaStJohns,
    #[sea_orm(string_value = "America/St_Kitts")]
    AmericaStKitts,
    #[sea_orm(string_value = "America/St_Lucia")]
    AmericaStLucia,
    #[sea_orm(string_value = "America/St_Thomas")]
    AmericaStThomas,
    #[sea_orm(string_value = "America/St_Vincent")]
    AmericaStVincent,
    #[sea_orm(string_value = "America/Swift_Current")]
    AmericaSwiftCurrent,
    #[sea_orm(string_value = "America/Tegucigalpa")]
    AmericaTegucigalpa,
    #[sea_orm(string_value = "America/Thule")]
    AmericaThule,
    #[sea_orm(string_value = "America/Thunder_Bay")]
    AmericaThunderBay,
    #[sea_orm(string_value = "America/Tijuana")]
    AmericaTijuana,
    #[sea_orm(string_value = "America/Toronto")]
    AmericaToronto,
    #[sea_orm(string_value = "America/Tortola")]
    AmericaTortola,
    #[sea_orm(string_value = "America/Vancouver")]
    AmericaVancouver,
    #[sea_orm(string_value = "America/Virgin")]
    AmericaVirgin,
    #[sea_orm(string_value = "America/Whitehorse")]
    AmericaWhitehorse,
    #[sea_orm(string_value = "America/Winnipeg")]
    AmericaWinnipeg,
    #[sea_orm(string_value = "America/Yakutat")]
    AmericaYakutat,
    #[sea_orm(string_value = "America/Yellowknife")]
    AmericaYellowknife,
    #[sea_orm(string_value = "Antarctica/Casey")]
    AntarcticaCasey,
    #[sea_orm(string_value = "Antarctica/Davis")]
    AntarcticaDavis,
    #[sea_orm(string_value = "Antarctica/DumontDUrville")]
    AntarcticaDumontDUrville,
    #[sea_orm(string_value = "Antarctica/Macquarie")]
    AntarcticaMacquarie,
    #[sea_orm(string_value = "Antarctica/Mawson")]
    AntarcticaMawson,
    #[sea_orm(string_value = "Antarctica/McMurdo")]
    AntarcticaMcMurdo,
    #[sea_orm(string_value = "Antarctica/Palmer")]
    AntarcticaPalmer,
    #[sea_orm(string_value = "Antarctica/Rothera")]
    AntarcticaRothera,
    #[sea_orm(string_value = "Antarctica/South_Pole")]
    AntarcticaSouthPole,
    #[sea_orm(string_value = "Antarctica/Syowa")]
    AntarcticaSyowa,
    #[sea_orm(string_value = "Antarctica/Troll")]
    AntarcticaTroll,
    #[sea_orm(string_value = "Antarctica/Vostok")]
    AntarcticaVostok,
    #[sea_orm(string_value = "Arctic/Longyearbyen")]
    ArcticLongyearbyen,
    #[sea_orm(string_value = "Asia/Aden")]
    AsiaAden,
    #[sea_orm(string_value = "Asia/Almaty")]
    AsiaAlmaty,
    #[sea_orm(string_value = "Asia/Amman")]
    AsiaAmman,
    #[sea_orm(string_value = "Asia/Anadyr")]
    AsiaAnadyr,
    #[sea_orm(string_value = "Asia/Aqtau")]
    AsiaAqtau,
    #[sea_orm(string_value = "Asia/Aqtobe")]
    AsiaAqtobe,
    #[sea_orm(string_value = "Asia/Ashgabat")]
    AsiaAshgabat,
    #[sea_orm(string_value = "Asia/Ashkhabad")]
    AsiaAshkhabad,
    #[sea_orm(string_value = "Asia/Atyrau")]
    AsiaAtyrau,
    #[sea_orm(string_value = "Asia/Baghdad")]
    AsiaBaghdad,
    #[sea_orm(string_value = "Asia/Bahrain")]
    AsiaBahrain,
    #[sea_orm(string_value = "Asia/Baku")]
    AsiaBaku,
    #[sea_orm(string_value = "Asia/Bangkok")]
    AsiaBangkok,
    #[sea_orm(string_value = "Asia/Barnaul")]
    AsiaBarnaul,
    #[sea_orm(string_value = "Asia/Beirut")]
    AsiaBeirut,
    #[sea_orm(string_value = "Asia/Bishkek")]
    AsiaBishkek,
    #[sea_orm(string_value = "Asia/Brunei")]
    AsiaBrunei,
    #[sea_orm(string_value = "Asia/Calcutta")]
    AsiaCalcutta,
    #[sea_orm(string_value = "Asia/Chita")]
    AsiaChita,
    #[sea_orm(string_value = "Asia/Choibalsan")]
    AsiaChoibalsan,
    #[sea_orm(string_value = "Asia/Chongqing")]
    AsiaChongqing,
    #[sea_orm(string_value = "Asia/Chungking")]
    AsiaChungking,
    #[sea_orm(string_value = "Asia/Colombo")]
    AsiaColombo,
    #[sea_orm(string_value = "Asia/Dacca")]
    AsiaDacca,
    #[sea_orm(string_value = "Asia/Damascus")]
    AsiaDamascus,
    #[sea_orm(string_value = "Asia/Dhaka")]
    AsiaDhaka,
    #[sea_orm(string_value = "Asia/Dili")]
    AsiaDili,
    #[sea_orm(string_value = "Asia/Dubai")]
    AsiaDubai,
    #[sea_orm(string_value = "Asia/Dushanbe")]
    AsiaDushanbe,
    #[sea_orm(string_value = "Asia/Famagusta")]
    AsiaFamagusta,
    #[sea_orm(string_value = "Asia/Gaza")]
    AsiaGaza,
    #[sea_orm(string_value = "Asia/Harbin")]
    AsiaHarbin,
    #[sea_orm(string_value = "Asia/Hebron")]
    AsiaHebron,
    #[sea_orm(string_value = "Asia/Ho_Chi_Minh")]
    AsiaHoChiMinh,
    #[sea_orm(string_value = "Asia/Hong_Kong")]
    AsiaHongKong,
    #[sea_orm(string_value = "Asia/Hovd")]
    AsiaHovd,
    #[sea_orm(string_value = "Asia/Irkutsk")]
    AsiaIrkutsk,
    #[sea_orm(string_value = "Asia/Istanbul")]
    AsiaIstanbul,
    #[sea_orm(string_value = "Asia/Jakarta")]
    AsiaJakarta,
    #[sea_orm(string_value = "Asia/Jayapura")]
    AsiaJayapura,
    #[sea_orm(string_value = "Asia/Jerusalem")]
    AsiaJerusalem,
    #[sea_orm(string_value = "Asia/Kabul")]
    AsiaKabul,
    #[sea_orm(string_value = "Asia/Kamchatka")]
    AsiaKamchatka,
    #[sea_orm(string_value = "Asia/Karachi")]
    AsiaKarachi,
    #[sea_orm(string_value = "Asia/Kashgar")]
    AsiaKashgar,
    #[sea_orm(string_value = "Asia/Kathmandu")]
    AsiaKathmandu,
    #[sea_orm(string_value = "Asia/Katmandu")]
    AsiaKatmandu,
    #[sea_orm(string_value = "Asia/Khandyga")]
    AsiaKhandyga,
    #[sea_orm(string_value = "Asia/Kolkata")]
    AsiaKolkata,
    #[sea_orm(string_value = "Asia/Krasnoyarsk")]
    AsiaKrasnoyarsk,
    #[sea_orm(string_value = "Asia/Kuala_Lumpur")]
    AsiaKualaLumpur,
    #[sea_orm(string_value = "Asia/Kuching")]
    AsiaKuching,
    #[sea_orm(string_value = "Asia/Kuwait")]
    AsiaKuwait,
    #[sea_orm(string_value = "Asia/Macao")]
    AsiaMacao,
    #[sea_orm(string_value = "Asia/Macau")]
    AsiaMacau,
    #[sea_orm(string_value = "Asia/Magadan")]
    AsiaMagadan,
    #[sea_orm(string_value = "Asia/Makassar")]
    AsiaMakassar,
    #[sea_orm(string_value = "Asia/Manila")]
    AsiaManila,
    #[sea_orm(string_value = "Asia/Muscat")]
    AsiaMuscat,
    #[sea_orm(string_value = "Asia/Nicosia")]
    AsiaNicosia,
    #[sea_orm(string_value = "Asia/Novokuznetsk")]
    AsiaNovokuznetsk,
    #[sea_orm(string_value = "Asia/Novosibirsk")]
    AsiaNovosibirsk,
    #[sea_orm(string_value = "Asia/Omsk")]
    AsiaOmsk,
    #[sea_orm(string_value = "Asia/Oral")]
    AsiaOral,
    #[sea_orm(string_value = "Asia/Phnom_Penh")]
    AsiaPhnomPenh,
    #[sea_orm(string_value = "Asia/Pontianak")]
    AsiaPontianak,
    #[sea_orm(string_value = "Asia/Pyongyang")]
    AsiaPyongyang,
    #[sea_orm(string_value = "Asia/Qatar")]
    AsiaQatar,
    #[sea_orm(string_value = "Asia/Qostanay")]
    AsiaQostanay,
    #[sea_orm(string_value = "Asia/Qyzylorda")]
    AsiaQyzylorda,
    #[sea_orm(string_value = "Asia/Rangoon")]
    AsiaRangoon,
    #[sea_orm(string_value = "Asia/Riyadh")]
    AsiaRiyadh,
    #[sea_orm(string_value = "Asia/Saigon")]
    AsiaSaigon,
    #[sea_orm(string_value = "Asia/Sakhalin")]
    AsiaSakhalin,
    #[sea_orm(string_value = "Asia/Samarkand")]
    AsiaSamarkand,
    #[sea_orm(string_value = "Asia/Seoul")]
    AsiaSeoul,
    #[sea_orm(string_value = "Asia/Shanghai")]
    AsiaShanghai,
    #[sea_orm(string_value = "Asia/Singapore")]
    AsiaSingapore,
    #[sea_orm(string_value = "Asia/Srednekolymsk")]
    AsiaSrednekolymsk,
    #[sea_orm(string_value = "Asia/Taipei")]
    AsiaTaipei,
    #[sea_orm(string_value = "Asia/Tashkent")]
    AsiaTashkent,
    #[sea_orm(string_value = "Asia/Tbilisi")]
    AsiaTbilisi,
    #[sea_orm(string_value = "Asia/Tehran")]
    AsiaTehran,
    #[sea_orm(string_value = "Asia/Tel_Aviv")]
    AsiaTelAviv,
    #[sea_orm(string_value = "Asia/Thimbu")]
    AsiaThimbu,
    #[sea_orm(string_value = "Asia/Thimphu")]
    AsiaThimphu,
    #[sea_orm(string_value = "Asia/Tokyo")]
    AsiaTokyo,
    #[sea_orm(string_value = "Asia/Tomsk")]
    AsiaTomsk,
    #[sea_orm(string_value = "Asia/Ujung_Pandang")]
    AsiaUjungPandang,
    #[sea_orm(string_value = "Asia/Ulaanbaatar")]
    AsiaUlaanbaatar,
    #[sea_orm(string_value = "Asia/Ulan_Bator")]
    AsiaUlanBator,
    #[sea_orm(string_value = "Asia/Urumqi")]
    AsiaUrumqi,
    #[sea_orm(string_value = "Asia/Ust-Nera")]
    AsiaUstNera,
    #[sea_orm(string_value = "Asia/Vientiane")]
    AsiaVientiane,
    #[sea_orm(string_value = "Asia/Vladivostok")]
    AsiaVladivostok,
    #[sea_orm(string_value = "Asia/Yakutsk")]
    AsiaYakutsk,
    #[sea_orm(string_value = "Asia/Yangon")]
    AsiaYangon,
    #[sea_orm(string_value = "Asia/Yekaterinburg")]
    AsiaYekaterinburg,
    #[sea_orm(string_value = "Asia/Yerevan")]
    AsiaYerevan,
    #[sea_orm(string_value = "Atlantic/Azores")]
    AtlanticAzores,
    #[sea_orm(string_value = "Atlantic/Bermuda")]
    AtlanticBermuda,
    #[sea_orm(string_value = "Atlantic/Canary")]
    AtlanticCanary,
    #[sea_orm(string_value = "Atlantic/Cape_Verde")]
    AtlanticCapeVerde,
    #[sea_orm(string_value = "Atlantic/Faeroe")]
    AtlanticFaeroe,
    #[sea_orm(string_value = "Atlantic/Faroe")]
    AtlanticFaroe,
    #[sea_orm(string_value = "Atlantic/Jan_Mayen")]
    AtlanticJanMayen,
    #[sea_orm(string_value = "Atlantic/Madeira")]
    AtlanticMadeira,
    #[sea_orm(string_value = "Atlantic/Reykjavik")]
    AtlanticReykjavik,
    #[sea_orm(string_value = "Atlantic/South_Georgia")]
    AtlanticSouthGeorgia,
    #[sea_orm(string_value = "Atlantic/St_Helena")]
    AtlanticStHelena,
    #[sea_orm(string_value = "Atlantic/Stanley")]
    AtlanticStanley,
    #[sea_orm(string_value = "Australia/ACT")]
    AustraliaAct,
    #[sea_orm(string_value = "Australia/Adelaide")]
    AustraliaAdelaide,
    #[sea_orm(string_value = "Australia/Brisbane")]
    AustraliaBrisbane,
    #[sea_orm(string_value = "Australia/Broken_Hill")]
    AustraliaBrokenHill,
    #[sea_orm(string_value = "Australia/Canberra")]
    AustraliaCanberra,
    #[sea_orm(string_value = "Australia/Currie")]
    AustraliaCurrie,
    #[sea_orm(string_value = "Australia/Darwin")]
    AustraliaDarwin,
    #[sea_orm(string_value = "Australia/Eucla")]
    AustraliaEucla,
    #[sea_orm(string_value = "Australia/Hobart")]
    AustraliaHobart,
    #[sea_orm(string_value = "Australia/LHI")]
    AustraliaLhi,
    #[sea_orm(string_value = "Australia/Lindeman")]
    AustraliaLindeman,
    #[sea_orm(string_value = "Australia/Lord_Howe")]
    AustraliaLordHowe,
    #[sea_orm(string_value = "Australia/Melbourne")]
    AustraliaMelbourne,
    #[sea_orm(string_value = "Australia/NSW")]
    AustraliaNsw,
    #[sea_orm(string_value = "Australia/North")]
    AustraliaNorth,
    #[sea_orm(string_value = "Australia/Perth")]
    AustraliaPerth,
    #[sea_orm(string_value = "Australia/Queensland")]
    AustraliaQueensland,
    #[sea_orm(string_value = "Australia/South")]
    AustraliaSouth,
    #[sea_orm(string_value = "Australia/Sydney")]
    AustraliaSydney,
    #[sea_orm(string_value = "Australia/Tasmania")]
    AustraliaTasmania,
    #[sea_orm(string_value = "Australia/Victoria")]
    AustraliaVictoria,
    #[sea_orm(string_value = "Australia/West")]
    AustraliaWest,
    #[sea_orm(string_value = "Australia/Yancowinna")]
    AustraliaYancowinna,
    #[sea_orm(string_value = "Brazil/Acre")]
    BrazilAcre,
    #[sea_orm(string_value = "Brazil/DeNoronha")]
    BrazilDeNoronha,
    #[sea_orm(string_value = "Brazil/East")]
    BrazilEast,
    #[sea_orm(string_value = "Brazil/West")]
    BrazilWest,
    #[sea_orm(string_value = "CET")]
    Cet,
    #[sea_orm(string_value = "CST6CDT")]
    Cst6cdt,
    #[sea_orm(string_value = "Canada/Atlantic")]
    CanadaAtlantic,
    #[sea_orm(string_value = "Canada/Central")]
    CanadaCentral,
    #[sea_orm(string_value = "Canada/Eastern")]
    CanadaEastern,
    #[sea_orm(string_value = "Canada/Mountain")]
    CanadaMountain,
    #[sea_orm(string_value = "Canada/Newfoundland")]
    CanadaNewfoundland,
    #[sea_orm(string_value = "Canada/Pacific")]
    CanadaPacific,
    #[sea_orm(string_value = "Canada/Saskatchewan")]
    CanadaSaskatchewan,
    #[sea_orm(string_value = "Canada/Yukon")]
    CanadaYukon,
    #[sea_orm(string_value = "Chile/Continental")]
    ChileContinental,
    #[sea_orm(string_value = "Chile/EasterIsland")]
    ChileEasterIsland,
    #[sea_orm(string_value = "Cuba")]
    Cuba,
    #[sea_orm(string_value = "EET")]
    Eet,
    #[sea_orm(string_value = "EST")]
    Est,
    #[sea_orm(string_value = "EST5EDT")]
    Est5edt,
    #[sea_orm(string_value = "Egypt")]
    Egypt,
    #[sea_orm(string_value = "Eire")]
    Eire,
    #[sea_orm(string_value = "Etc/GMT")]
    EtcGmt,
    #[sea_orm(string_value = "Etc/GMT+0")]
    EtcGmt0,
    #[sea_orm(string_value = "Etc/GMT+1")]
    EtcGmt1,
    #[sea_orm(string_value = "Etc/GMT+10")]
    EtcGmt10,
    #[sea_orm(string_value = "Etc/GMT+11")]
    EtcGmt11,
    #[sea_orm(string_value = "Etc/GMT+12")]
    EtcGmt12,
    #[sea_orm(string_value = "Etc/GMT+2")]
    EtcGmt2,
    #[sea_orm(string_value = "Etc/GMT+3")]
    EtcGmt3,
    #[sea_orm(string_value = "Etc/GMT+4")]
    EtcGmt4,
    #[sea_orm(string_value = "Etc/GMT+5")]
    EtcGmt5,
    #[sea_orm(string_value = "Etc/GMT+6")]
    EtcGmt6,
    #[sea_orm(string_value = "Etc/GMT+7")]
    EtcGmt7,
    #[sea_orm(string_value = "Etc/GMT+8")]
    EtcGmt8,
    #[sea_orm(string_value = "Etc/GMT+9")]
    EtcGmt9,
    #[sea_orm(string_value = "Etc/GMT-0")]
    EtcGmt0,
    #[sea_orm(string_value = "Etc/GMT-1")]
    EtcGmt1,
    #[sea_orm(string_value = "Etc/GMT-10")]
    EtcGmt10,
    #[sea_orm(string_value = "Etc/GMT-11")]
    EtcGmt11,
    #[sea_orm(string_value = "Etc/GMT-12")]
    EtcGmt12,
    #[sea_orm(string_value = "Etc/GMT-13")]
    EtcGmt13,
    #[sea_orm(string_value = "Etc/GMT-14")]
    EtcGmt14,
    #[sea_orm(string_value = "Etc/GMT-2")]
    EtcGmt2,
    #[sea_orm(string_value = "Etc/GMT-3")]
    EtcGmt3,
    #[sea_orm(string_value = "Etc/GMT-4")]
    EtcGmt4,
    #[sea_orm(string_value = "Etc/GMT-5")]
    EtcGmt5,
    #[sea_orm(string_value = "Etc/GMT-6")]
    EtcGmt6,
    #[sea_orm(string_value = "Etc/GMT-7")]
    EtcGmt7,
    #[sea_orm(string_value = "Etc/GMT-8")]
    EtcGmt8,
    #[sea_orm(string_value = "Etc/GMT-9")]
    EtcGmt9,
    #[sea_orm(string_value = "Etc/GMT0")]
    EtcGmt0,
    #[sea_orm(string_value = "Etc/Greenwich")]
    EtcGreenwich,
    #[sea_orm(string_value = "Etc/UCT")]
    EtcUct,
    #[sea_orm(string_value = "Etc/UTC")]
    EtcUtc,
    #[sea_orm(string_value = "Etc/Universal")]
    EtcUniversal,
    #[sea_orm(string_value = "Etc/Zulu")]
    EtcZulu,
    #[sea_orm(string_value = "Europe/Amsterdam")]
    EuropeAmsterdam,
    #[sea_orm(string_value = "Europe/Andorra")]
    EuropeAndorra,
    #[sea_orm(string_value = "Europe/Astrakhan")]
    EuropeAstrakhan,
    #[sea_orm(string_value = "Europe/Athens")]
    EuropeAthens,
    #[sea_orm(string_value = "Europe/Belfast")]
    EuropeBelfast,
    #[sea_orm(string_value = "Europe/Belgrade")]
    EuropeBelgrade,
    #[sea_orm(string_value = "Europe/Berlin")]
    EuropeBerlin,
    #[sea_orm(string_value = "Europe/Bratislava")]
    EuropeBratislava,
    #[sea_orm(string_value = "Europe/Brussels")]
    EuropeBrussels,
    #[sea_orm(string_value = "Europe/Bucharest")]
    EuropeBucharest,
    #[sea_orm(string_value = "Europe/Budapest")]
    EuropeBudapest,
    #[sea_orm(string_value = "Europe/Busingen")]
    EuropeBusingen,
    #[sea_orm(string_value = "Europe/Chisinau")]
    EuropeChisinau,
    #[sea_orm(string_value = "Europe/Copenhagen")]
    EuropeCopenhagen,
    #[sea_orm(string_value = "Europe/Dublin")]
    EuropeDublin,
    #[sea_orm(string_value = "Europe/Gibraltar")]
    EuropeGibraltar,
    #[sea_orm(string_value = "Europe/Guernsey")]
    EuropeGuernsey,
    #[sea_orm(string_value = "Europe/Helsinki")]
    EuropeHelsinki,
    #[sea_orm(string_value = "Europe/Isle_of_Man")]
    EuropeIsleOfMan,
    #[sea_orm(string_value = "Europe/Istanbul")]
    EuropeIstanbul,
    #[sea_orm(string_value = "Europe/Jersey")]
    EuropeJersey,
    #[sea_orm(string_value = "Europe/Kaliningrad")]
    EuropeKaliningrad,
    #[sea_orm(string_value = "Europe/Kiev")]
    EuropeKiev,
    #[sea_orm(string_value = "Europe/Kirov")]
    EuropeKirov,
    #[sea_orm(string_value = "Europe/Lisbon")]
    EuropeLisbon,
    #[sea_orm(string_value = "Europe/Ljubljana")]
    EuropeLjubljana,
    #[sea_orm(string_value = "Europe/London")]
    EuropeLondon,
    #[sea_orm(string_value = "Europe/Luxembourg")]
    EuropeLuxembourg,
    #[sea_orm(string_value = "Europe/Madrid")]
    EuropeMadrid,
    #[sea_orm(string_value = "Europe/Malta")]
    EuropeMalta,
    #[sea_orm(string_value = "Europe/Mariehamn")]
    EuropeMariehamn,
    #[sea_orm(string_value = "Europe/Minsk")]
    EuropeMinsk,
    #[sea_orm(string_value = "Europe/Monaco")]
    EuropeMonaco,
    #[sea_orm(string_value = "Europe/Moscow")]
    EuropeMoscow,
    #[sea_orm(string_value = "Europe/Nicosia")]
    EuropeNicosia,
    #[sea_orm(string_value = "Europe/Oslo")]
    EuropeOslo,
    #[sea_orm(string_value = "Europe/Paris")]
    EuropeParis,
    #[sea_orm(string_value = "Europe/Podgorica")]
    EuropePodgorica,
    #[sea_orm(string_value = "Europe/Prague")]
    EuropePrague,
    #[sea_orm(string_value = "Europe/Riga")]
    EuropeRiga,
    #[sea_orm(string_value = "Europe/Rome")]
    EuropeRome,
    #[sea_orm(string_value = "Europe/Samara")]
    EuropeSamara,
    #[sea_orm(string_value = "Europe/San_Marino")]
    EuropeSanMarino,
    #[sea_orm(string_value = "Europe/Sarajevo")]
    EuropeSarajevo,
    #[sea_orm(string_value = "Europe/Saratov")]
    EuropeSaratov,
    #[sea_orm(string_value = "Europe/Simferopol")]
    EuropeSimferopol,
    #[sea_orm(string_value = "Europe/Skopje")]
    EuropeSkopje,
    #[sea_orm(string_value = "Europe/Sofia")]
    EuropeSofia,
    #[sea_orm(string_value = "Europe/Stockholm")]
    EuropeStockholm,
    #[sea_orm(string_value = "Europe/Tallinn")]
    EuropeTallinn,
    #[sea_orm(string_value = "Europe/Tirane")]
    EuropeTirane,
    #[sea_orm(string_value = "Europe/Tiraspol")]
    EuropeTiraspol,
    #[sea_orm(string_value = "Europe/Ulyanovsk")]
    EuropeUlyanovsk,
    #[sea_orm(string_value = "Europe/Uzhgorod")]
    EuropeUzhgorod,
    #[sea_orm(string_value = "Europe/Vaduz")]
    EuropeVaduz,
    #[sea_orm(string_value = "Europe/Vatican")]
    EuropeVatican,
    #[sea_orm(string_value = "Europe/Vienna")]
    EuropeVienna,
    #[sea_orm(string_value = "Europe/Vilnius")]
    EuropeVilnius,
    #[sea_orm(string_value = "Europe/Volgograd")]
    EuropeVolgograd,
    #[sea_orm(string_value = "Europe/Warsaw")]
    EuropeWarsaw,
    #[sea_orm(string_value = "Europe/Zagreb")]
    EuropeZagreb,
    #[sea_orm(string_value = "Europe/Zaporozhye")]
    EuropeZaporozhye,
    #[sea_orm(string_value = "Europe/Zurich")]
    EuropeZurich,
    #[sea_orm(string_value = "GB")]
    Gb,
    #[sea_orm(string_value = "GB-Eire")]
    GbEire,
    #[sea_orm(string_value = "GMT")]
    Gmt,
    #[sea_orm(string_value = "GMT+0")]
    Gmt0,
    #[sea_orm(string_value = "GMT-0")]
    Gmt0,
    #[sea_orm(string_value = "GMT0")]
    Gmt0,
    #[sea_orm(string_value = "Greenwich")]
    Greenwich,
    #[sea_orm(string_value = "HST")]
    Hst,
    #[sea_orm(string_value = "Hongkong")]
    Hongkong,
    #[sea_orm(string_value = "Iceland")]
    Iceland,
    #[sea_orm(string_value = "Indian/Antananarivo")]
    IndianAntananarivo,
    #[sea_orm(string_value = "Indian/Chagos")]
    IndianChagos,
    #[sea_orm(string_value = "Indian/Christmas")]
    IndianChristmas,
    #[sea_orm(string_value = "Indian/Cocos")]
    IndianCocos,
    #[sea_orm(string_value = "Indian/Comoro")]
    IndianComoro,
    #[sea_orm(string_value = "Indian/Kerguelen")]
    IndianKerguelen,
    #[sea_orm(string_value = "Indian/Mahe")]
    IndianMahe,
    #[sea_orm(string_value = "Indian/Maldives")]
    IndianMaldives,
    #[sea_orm(string_value = "Indian/Mauritius")]
    IndianMauritius,
    #[sea_orm(string_value = "Indian/Mayotte")]
    IndianMayotte,
    #[sea_orm(string_value = "Indian/Reunion")]
    IndianReunion,
    #[sea_orm(string_value = "Iran")]
    Iran,
    #[sea_orm(string_value = "Israel")]
    Israel,
    #[sea_orm(string_value = "Jamaica")]
    Jamaica,
    #[sea_orm(string_value = "Japan")]
    Japan,
    #[sea_orm(string_value = "Kwajalein")]
    Kwajalein,
    #[sea_orm(string_value = "Libya")]
    Libya,
    #[sea_orm(string_value = "MET")]
    Met,
    #[sea_orm(string_value = "MST")]
    Mst,
    #[sea_orm(string_value = "MST7MDT")]
    Mst7mdt,
    #[sea_orm(string_value = "Mexico/BajaNorte")]
    MexicoBajaNorte,
    #[sea_orm(string_value = "Mexico/BajaSur")]
    MexicoBajaSur,
    #[sea_orm(string_value = "Mexico/General")]
    MexicoGeneral,
    #[sea_orm(string_value = "NZ")]
    Nz,
    #[sea_orm(string_value = "NZ-CHAT")]
    NzChat,
    #[sea_orm(string_value = "Navajo")]
    Navajo,
    #[sea_orm(string_value = "PRC")]
    Prc,
    #[sea_orm(string_value = "PST8PDT")]
    Pst8pdt,
    #[sea_orm(string_value = "Pacific/Apia")]
    PacificApia,
    #[sea_orm(string_value = "Pacific/Auckland")]
    PacificAuckland,
    #[sea_orm(string_value = "Pacific/Bougainville")]
    PacificBougainville,
    #[sea_orm(string_value = "Pacific/Chatham")]
    PacificChatham,
    #[sea_orm(string_value = "Pacific/Chuuk")]
    PacificChuuk,
    #[sea_orm(string_value = "Pacific/Easter")]
    PacificEaster,
    #[sea_orm(string_value = "Pacific/Efate")]
    PacificEfate,
    #[sea_orm(string_value = "Pacific/Enderbury")]
    PacificEnderbury,
    #[sea_orm(string_value = "Pacific/Fakaofo")]
    PacificFakaofo,
    #[sea_orm(string_value = "Pacific/Fiji")]
    PacificFiji,
    #[sea_orm(string_value = "Pacific/Funafuti")]
    PacificFunafuti,
    #[sea_orm(string_value = "Pacific/Galapagos")]
    PacificGalapagos,
    #[sea_orm(string_value = "Pacific/Gambier")]
    PacificGambier,
    #[sea_orm(string_value = "Pacific/Guadalcanal")]
    PacificGuadalcanal,
    #[sea_orm(string_value = "Pacific/Guam")]
    PacificGuam,
    #[sea_orm(string_value = "Pacific/Honolulu")]
    PacificHonolulu,
    #[sea_orm(string_value = "Pacific/Johnston")]
    PacificJohnston,
    #[sea_orm(string_value = "Pacific/Kanton")]
    PacificKanton,
    #[sea_orm(string_value = "Pacific/Kiritimati")]
    PacificKiritimati,
    #[sea_orm(string_value = "Pacific/Kosrae")]
    PacificKosrae,
    #[sea_orm(string_value = "Pacific/Kwajalein")]
    PacificKwajalein,
    #[sea_orm(string_value = "Pacific/Majuro")]
    PacificMajuro,
    #[sea_orm(string_value = "Pacific/Marquesas")]
    PacificMarquesas,
    #[sea_orm(string_value = "Pacific/Midway")]
    PacificMidway,
    #[sea_orm(string_value = "Pacific/Nauru")]
    PacificNauru,
    #[sea_orm(string_value = "Pacific/Niue")]
    PacificNiue,
    #[sea_orm(string_value = "Pacific/Norfolk")]
    PacificNorfolk,
    #[sea_orm(string_value = "Pacific/Noumea")]
    PacificNoumea,
    #[sea_orm(string_value = "Pacific/Pago_Pago")]
    PacificPagoPago,
    #[sea_orm(string_value = "Pacific/Palau")]
    PacificPalau,
    #[sea_orm(string_value = "Pacific/Pitcairn")]
    PacificPitcairn,
    #[sea_orm(string_value = "Pacific/Pohnpei")]
    PacificPohnpei,
    #[sea_orm(string_value = "Pacific/Ponape")]
    PacificPonape,
    #[sea_orm(string_value = "Pacific/Port_Moresby")]
    PacificPortMoresby,
    #[sea_orm(string_value = "Pacific/Rarotonga")]
    PacificRarotonga,
    #[sea_orm(string_value = "Pacific/Saipan")]
    PacificSaipan,
    #[sea_orm(string_value = "Pacific/Samoa")]
    PacificSamoa,
    #[sea_orm(string_value = "Pacific/Tahiti")]
    PacificTahiti,
    #[sea_orm(string_value = "Pacific/Tarawa")]
    PacificTarawa,
    #[sea_orm(string_value = "Pacific/Tongatapu")]
    PacificTongatapu,
    #[sea_orm(string_value = "Pacific/Truk")]
    PacificTruk,
    #[sea_orm(string_value = "Pacific/Wake")]
    PacificWake,
    #[sea_orm(string_value = "Pacific/Wallis")]
    PacificWallis,
    #[sea_orm(string_value = "Pacific/Yap")]
    PacificYap,
    #[sea_orm(string_value = "Poland")]
    Poland,
    #[sea_orm(string_value = "Portugal")]
    Portugal,
    #[sea_orm(string_value = "ROC")]
    Roc,
    #[sea_orm(string_value = "ROK")]
    Rok,
    #[sea_orm(string_value = "Singapore")]
    Singapore,
    #[sea_orm(string_value = "Turkey")]
    Turkey,
    #[sea_orm(string_value = "UCT")]
    Uct,
    #[sea_orm(string_value = "US/Alaska")]
    UsAlaska,
    #[sea_orm(string_value = "US/Aleutian")]
    UsAleutian,
    #[sea_orm(string_value = "US/Arizona")]
    UsArizona,
    #[sea_orm(string_value = "US/Central")]
    UsCentral,
    #[sea_orm(string_value = "US/East-Indiana")]
    UsEastIndiana,
    #[sea_orm(string_value = "US/Eastern")]
    UsEastern,
    #[sea_orm(string_value = "US/Hawaii")]
    UsHawaii,
    #[sea_orm(string_value = "US/Indiana-Starke")]
    UsIndianaStarke,
    #[sea_orm(string_value = "US/Michigan")]
    UsMichigan,
    #[sea_orm(string_value = "US/Mountain")]
    UsMountain,
    #[sea_orm(string_value = "US/Pacific")]
    UsPacific,
    #[sea_orm(string_value = "US/Samoa")]
    UsSamoa,
    #[sea_orm(string_value = "UTC")]
    Utc,
    #[sea_orm(string_value = "Universal")]
    Universal,
    #[sea_orm(string_value = "W-SU")]
    WSu,
    #[sea_orm(string_value = "WET")]
    Wet,
    #[sea_orm(string_value = "Zulu")]
    Zulu,
}
